select * from dual;

--오라클 구 버전 방식으로 계정 생성가능하도록 설정
alter session set "_ORACLE_SCRIPT"=true;

-- DASQL 계정을 생성
CREATE user DASQL identified by 0805;
alter user DASQL account unlock;
grant resource, dba, connect to DASQL;

CREATE TABLESPACE DASQL_DATA
datafile 'C:\app\dcu\product\18.0.0\oradata\XE\DASQL_DATA.dbf' SIZE 2G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE DASQL_TEMP
TEMPFILE 'C:\app\dcu\product\18.0.0\oradata\XE\DASQL_TEMP.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER DASQL DEFAULT TABLESPACE DASQL_DATA;
ALTER USER DASQL TEMPORARY TABLESPACE DASQL_TEMP;


-------------------------------------------------------------
--오라클 구 버전 방식으로 계정 생성가능하도록 설정
alter session set "_ORACLE_SCRIPT"=true;

-- DASQL 계정을 생성
CREATE user WEBSQL identified by 0805;
alter user WEBSQL account unlock;
grant resource, dba, connect to WEBSQL;

CREATE TABLESPACE WEBSQL_DATA
datafile 'C:\app\dcu\product\18.0.0\oradata\XE\WEBSQL_DATA.dbf' SIZE 2G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE WEBSQL_TEMP
TEMPFILE 'C:\app\dcu\product\18.0.0\oradata\XE\WEBSQL_TEMP.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER WEBSQL DEFAULT TABLESPACE WEBSQL_DATA;
ALTER USER WEBSQL TEMPORARY TABLESPACE WEBSQL_TEMP;









