--오라클 구 버전 방식으로 계정 생성가능하도록 설정 
alter session set "_ORACLE_SCRIPT"=true;

-- DASQL 계정을 생성 
CREATE user DASQL identified by 0805; 
alter user DASQL account unlock; 
grant resource, dba, connect to DASQL;

CREATE TABLESPACE DASQL_DATA datafile 'C:\app\user\product\18.0.0\oradata\XE\DASQL_DATA.dbf' SIZE 2G AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE TEMPORARY TABLESPACE DASQL_TEMP TEMPFILE 'C:\app\user\product\18.0.0\oradata\XE\DASQL_TEMP.dbf' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;



-- PETS 계정을 생성
CREATE user PETS identified by 0805;
alter user PETS account unlock;
grant resource, dba, connect to PETS;

CREATE TABLESPACE PETS_DATA datafile 'C:\app\user\product\18.0.0\oradata\XE\PETS_DATA.dbf' SIZE 2G AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE TEMPORARY TABLESPACE PETS_TEMP TEMPFILE 'C:\app\user\product\18.0.0\oradata\XE\PETS_TEMP.dbf' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;